### ISSUE TITLE
Stuff Karissa is working on

### ISSUE THREAD

**Issue by okdistribute** [datproject/planning#11]
# Organization
- [x] Work with @RangerMauve and @joehand to update the dat.foundation website according to @whoisgina's recommendations
- [ ] Clean up repositories & structure for the datprotocol/datproject/dat-land organizations
- [x] Work with working groups to clearly define bylaws & membership
- [x] Write a blog post about upcoming dat 2.0 movements
- [x] Write blog post about upcoming organizational goals
- [ ] Easily get metrics about who is using dat & contributing
- [x] Move blog to blog.dat.foundation
- [x] Get the consortium started

# Engineering/product management
- [x] List all the changes that will need to happen in documentation & deprecation due to dat 2.0 (https://github.com/datproject/docs/issues/165)
- [x] Find a champion for CLI updates for dat 2.0
- [x] More clearly deprecate dat base

# Fundraising
- [x] Apply to [NLNet Privacy call](https://nlnet.nl/PET/) by Oct 1 2019
- ~~[ ] Apply to the [H2020 ICT call](https://www.ngi.eu/news/2019/08/07/h2020-ict-calls-are-open-lets-build-the-internet-of-humans/) by Nov 13 2019~~
- [x] Follow up with California Digital Library about supporting dat-store & cli work
- [ ] Follow up with various fundraising leads (i.e., endless coffee and lunch dates and video calls...) ((this box will never be checked))
- [x] Create gitcoin account for dat https://gitcoin.co/grants/132/the-dat-protocol

**Comment by okdistribute** [comment]
I have no more things on my plate, I'm moving on!

**Comment by martinheidegger** [comment]
Does it mean that this is outdated ↓
<img width="1279" alt="Screen Shot 2020-05-16 at 01 32 35" src="https://user-images.githubusercontent.com/914122/82074060-250df300-9715-11ea-9eb0-fadaa7f68891.png">
