### ISSUE TITLE
HyperSwarm

### ISSUE THREAD

**Issue by martinheidegger** [datproject/planning#3]
As far as I was able to tell: there is a lot of effort happening in regards to HyperSwarm?! Where does this fit in the planning process?

**Comment by joehand** [comment]
Yes, [hyperswarm](https://github.com/hyperswarm) is where most of the [network improvements](https://github.com/datproject/planning#networking-improvements) are happening (for those unfamiliar). Its happening alongside multiwriter, but may not be clear in the doc.

Is there something we can do to clarify that section or how it relates to the rest?
