### ISSUE TITLE
Linking to issues.

### ISSUE THREAD

**Issue by martinheidegger** [datproject/planning#4]
I am not sure if github projects would be the right way to go: but It would be nice to see a list of issues/repos to follow in order to understand where the work is ongoing on - for example - the trie implementation.

**Comment by okdistribute** [comment]
+1 on having a github project that just sort of catalogues things across repos

**Comment by joehand** [comment]
This would be great! Do y'all have any idea how we can link issues across organizations? Unfortunately, github projects limit us to issues within the datproject org while development will be happening in a lot of orgs.

**Comment by RangerMauve** [comment]
I would suggest having a markdown file with links. Just adding links in the README would be a huge improvement.
