### ISSUE TITLE
State of Dat

### ISSUE THREAD

**Issue by joehand** [datproject/planning#6]
> PS. I think one thing that would help is a good “State of DAT” page that lists the relevant/currently-being-worked on modules/projects (out of the dozens) and documentation and has pathways to discovery for people interesting in using, developing with, and porting DAT. Something short, concise, and frequently updated.

Yes! This would be great to do 1-2x/month (or at every #datprotocol meeting)

**Comment by todrobbins** [comment]
Any update on State of Dat? I'd be happy to contribute.

**Comment by joehand** [comment]
@todrobbins there are weekly meetings via[ comm-comm](https://comm-comm.datproject.org) that covers a lot of this. But having something written would also be great.

**Comment by okdistribute** [comment]
Yeah it would be great to have a newsletter.

**Comment by RangerMauve** [comment]
I'd be up for setting up a newsletter. :O I've actually been looking into it a little lately.

**Comment by todrobbins** [comment]
@RangerMauve happy to help with a newsletter 👍🏻

**Comment by joehand** [comment]
We have a mailchip list with ~500 people subscribed via the blog

**Comment by RangerMauve** [comment]
Awesome!

@joehand do you think I could get access to Mailchimp?

@todrobbins What sort of stuff would you be interested in doing newsletter-wise?

I'll start looking into setting up the pumbing for the newsletter next week. Maybe also reach out to people to see what they'd like to see from a Dat newsletter on IRC and Twitter.

**Comment by okdistribute** [comment]
This is now in https://github.com/datproject/newsletter
