### ISSUE TITLE
Stuff Joe Hand is working on

### ISSUE THREAD

**Issue by joehand** [datproject/planning#8]
* Updating dat-node and related dependencies to use promises, other nicer es6 features as we drop Node v6.
  * dat-node https://github.com/datproject/dat-node/pull/235
  * dat-node v4 https://github.com/datproject/dat-node/pull/243
  * dat v14 https://github.com/datproject/dat/pull/1125
* multi-archive swarms in dat-node
  * allow passing in of existing swarm to dat-node to join instead of create new (hyperdiscovery v9)
* MOSS:
  * working with Gina on DatX

**Comment by todrobbins** [comment]
![tenor](https://user-images.githubusercontent.com/158590/56620938-deb89400-65e7-11e9-9893-8ed6fedf33cf.gif)
What about multi-writer though?

**Comment by okdistribute** [comment]
@todrobbins hey, good question :) @andrewosh is working on that!

**Comment by todrobbins** [comment]
Would love to see an "Stuff @andrewosh is working on" issue. 😄
