### ISSUE TITLE
Hypercores in Beaker

### ISSUE THREAD

**Issue by RangerMauve** [datproject/planning#9]
Here's the roadmap for getting hypercore based applications to work in Beaker.

Some motivation: It's hard to get Node.js based applications deployed since bundling electron is a pain to do and convince people to install, and Beaker doesn't yet have the APIs needed to make them work without it. The [Peer Socket](https://github.com/beakerbrowser/beaker-core/pull/6) API will help since we'd be able to do general networking, sadly it's blocked on Hyperswarm being out, and on integrating Noise for transport level encryption (sending stuff through the clear and making developers do encryption is bad UX).

Ideally we should focus on the minimal set of features to enable these use cases.

- Should have access to most if not all hypercore APIs
- Should be easy to wrap to make it look like the regular hypercore API
- Hypercores should be able to swarm over a single key
- Should be able to send / listen on extension messages to enable [multiwriter](https://github.com/kappa-db/multifeed/blob/master/mux.js#L21)

Roadmap:

- Draft up Beaker API
- Implement over top of regular hypercore and hyperdiscovery in Node
- Create wrapper that looks like regular hypercore
- Test with multifeed
- Implement in Beaker
- 🎉🎉🎉

cc @pfrazee @noffle

**Comment by RangerMauve** [comment]
@pfrazee What's the minimal amount of UI we can get away with in Beaker?

I'm thinking that as an MVP we could get away with not having an analog to `selectArchive` or fancy UIs for viewing it. I think it'd be good to tag hypercores with which archive created them, and make it easy to delete them based on that. Thoughts?

**Comment by pfrazee** [comment]
@RangerMauve I'm not totally sure yet, I'm in the middle of that work right now. I'll keep you updated.

**Comment by okdistribute** [comment]
It sounds like this will get punted down the road?

**Comment by RangerMauve** [comment]
Yeah.... way down the road by the looks of it. :P Might as well close it for now until it's actively being worked on.
